server:
  port: 9001
dubbo:
  application:
    name: checkup_controller
  protocol:
    name: dubbo
    port: 20881
  registry:
    protocol: zookeeper
    address: 39.107.239.26:2181,39.107.239.26:2182,39.107.239.26:2183
  scan:
    base-packages: com.checkup.controller
  consumer:
    timeout: 3000
spring:
  redis:
    host: 39.107.239.26
    port: 6379
    password: redis123
  devtools:
    restart:
      enabled: true
      additional-exclude: src/main/java
  servlet:
    multipart:
      max-file-size: 2MB
  web:
    resources:
      static-locations: classpath:/public,classpath:/static,classpath:/META-INF/resources,classpath:/resources,file:///C:\Users\dell\Desktop\checkup
setmeal_img_path: C:\Users\dell\Desktop\checkup