server:
  port: 8001
dubbo:
  application:
    name: checkup_provider
  protocol:
    name: dubbo
    port: 20881
  registry:
    #address: zookeeper://39.107.239.26:2181?backup=39.107.239.26:2182,39.107.239.26:2183
    protocol: zookeeper
    address: 39.107.239.26:2181,39.107.239.26:2182,39.107.239.26:2183
  scan:
    base-packages: com.checkup.service.impl
  provider:
    timeout: 3000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.107.239.26:3306/offcnpe?characterEncoding=utf-8
    username: ldq
    password: "*!%9$ZKm6z"
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    #开启驼峰标识
    map-underscore-to-camel-case: true
    #控制台SQL输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    #逻辑删除
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0
  #加载xml文件
  mapper-locations: classpath:/mappers/xml/*.xml
  type-aliases-package: com.checkup.pojo
setmeal_img_path: C:\Users\dell\Desktop\checkup
